### ISSUE TITLE
[SUGGESTION] New dead state

### ISSUE THREAD

**Issue by TonybynMp4** [Qbox-project/qb-ambulancejob#24]
A K.O state similar to the laststand but you could get up after 60 seconds for example, would be used on minor injuries (fist fights for example) while gun injuries etc would still make you go in laststand.
and maybe just make the player ragdoll instead of an animation ? (feels more logical)

**Comment by Manason** [comment]
We already do have a brain damage effect if the player takes damage to the head which blacks them out for a few seconds and causes them to rag doll. We could re-use that easily and extend the time for certain blunt force traumas to the head?

I really like the rag doll suggestion in general. I think we should look into replacing the last stand animation with it.

**Comment by TonybynMp4** [comment]
Sounds good to me 😊
