### ISSUE TITLE
[BUG] Occasionally not going into last stand, can't revive

### ISSUE THREAD

**Issue by JustDeltaAU** [Qbox-project/qb-ambulancejob#51]
### Summary

Using the latest files, on some occasions when you 'die', you fall down but don't get placed into last stand, therefore can't be helped.

### Reproduction

Kill yourself naturally. I've noticed it MAY happen more when you're just standing in one place, and die due to hunger/thirst, but can't confirm this as it also works perfectly fine when dying to hunger/thirst some times as well.

### Expected behavior

Get placed into last stand, wait your timer out before you can respawn.

### Actual behavior

You fall down, there's no timer displayed, and you're unable to use /revive or any form of admin commands, including txAdmin to heal yourself. You're infinitely laying on the ground until you leave the server and rejoin.

### Last Updated

Today

### Custom Resources

No.

### Resource Rename

No.

**Comment by mockdot** [comment]
Could you retry with the latest build? This should be fixed.

**Comment by mockdot** [comment]
This has been resolved.
