### ISSUE TITLE
[SUGGESTION] Tell bleeding out player whether EMS is on duty

### ISSUE THREAD

**Issue by Manason** [Qbox-project/qb-ambulancejob#6]
**Is your feature request related to a problem? Please describe.**
A player bleeding out or has already bled out may be ok waiting for EMS to arrive, but does not know whether anyone is coming or not.

**Describe the feature you'd like**
The 3d text that displays to the downed user should call qb-core to check whether any EMS are on duty and relay that info to the player.

**Describe alternatives you've considered**
Not showing the option to call EMS if none are online, but this has some edge cases. Like what happens if an EMS comes online during, or goes offline after they are called.

**Comment by YvanCywan** [comment]
This is a decent suggestion. The alternative solution you described should actually work since the code is read over again in the thread while the player is down. Meaning that if EMS comes online, the button should change to allow you to call medics.

**Comment by HebiKotei** [comment]
take

**Comment by Manason** [comment]
I don't know if I broke this due to my refactors or whether it was already like this, but the current behavior is that it shows the button regardless of whether EMS are online or not. The player can continue to press it with no results unless EMS is online in which case the button goes away and the text is replaced. It should check for EMS being on duty before showing the button in the first place.
