### ISSUE TITLE
CheckIn

### ISSUE THREAD

**Issue by BigSmoKe07** [Qbox-project/qb-ambulancejob#76]
### Summary

The checkin keypress doesnt work

### Reproduction

the Check in  is not getting the keypressed 

### Expected behavior

i have already tried printing the values 

### Actual behavior

.

### Last Updated

last commit

### Custom Resources

no

### Resource Rename

no

**Comment by BigSmoKe07** [comment]
targets are fine , the only problem is with checkInControls

**Comment by Manason** [comment]
Any errors?

**Comment by BigSmoKe07** [comment]
no
 I also tried printing  in the function put no output

**Comment by mockdot** [comment]
This has been fixed with #87, closing this.
