### ISSUE TITLE
[SUGGESTION] Female Health Handling for Parity with Males

### ISSUE THREAD

**Issue by Manason** [Qbox-project/qb-ambulancejob#8]
**Is your feature request related to a problem? Please describe.**
In native GTA, female peds have 75% of the health of male peds. This isn't realistic and incentivizes player's against playing female characters.

**Describe the feature you'd like**
starting health should be set the same for males and females. One possible way to do this is to change the health UI to be percentage based, and also modify the incoming damage to a player based on their max health. I'm just spitballing though as I haven't given the implementation details much thought.

**Describe alternatives you've considered**
Wondering if the SetEntityMaxHealth could be done on player load-in to ensure everyone is at the same value, and then on character creation, the health could be set to entity max health. This could even have the benefit of a config value to determine max health so server's can set it higher or lower for all players.

**Comment by ChatDisabled** [comment]
Theoretically fixed with https://github.com/Qbox-project/qb-ambulancejob/pull/9
