### ISSUE TITLE
EMS request help text flickering

### ISSUE THREAD

**Issue by maguhd** [Qbox-project/qb-ambulancejob#82]
### Summary

EMS request help text flickering

### Reproduction

1. Die
2. Wait 60 seconds or whatever time you've set up.
3. EMS request text flickering.
4. Wait untill time is up
5. HOLD E FOR 5 SECONDS and nothing happens
6. The text of the seconds skip from 2 to 0
7. Does not respawn...if i take my hand off E the timer reset to 5.
8. If I revive myself by command I get revived but the character is still playing the dead or laststand animation.

Also when dying of thirst of hunger or both, the laststand animation starts but no countdown text.

### Expected behavior

Not flicker
Not skip from 2 seconds to 0 and actually respawn.
Cancel dead and laststand animation

### Actual behavior

Text flickering and not respawning.
Also when dying of thirst of hunger or both, the laststand animation starts but no countdown text.

### Last Updated

Today

### Custom Resources

No

### Resource Rename

No

**Comment by maguhd** [comment]
I added the last 2 commits from Aug 26, 2023.
Now the player is beeing spawned in bed.
While he is in bed (on the left side) there is a popup to press E to lay in bed. (that shouldnt be there while already beeing in bed).
After waiting a bit, the player gets treated, but the animation of laying in bed is canceled and the text to get out of bed pops up. After pressing E to get out of bed, the players does the animation and gets out of bed, but getting this error https://i.imgur.com/SkrIrLt.png

**Comment by Manason** [comment]
> I added the last 2 commits from Aug 26, 2023.
> Now the player is beeing spawned in bed.
> While he is in bed (on the left side) there is a popup to press E to lay in bed. (that shouldnt be there while already beeing in bed).
> After waiting a bit, the player gets treated, but the animation of laying in bed is canceled and the text to get out of bed pops up. After pressing E to get out of bed, the players does the animation and gets out of bed, but getting this error https://i.imgur.com/SkrIrLt.png

#87 Should fix most if not all of these issues.

**Comment by maguhd** [comment]
> I added the last 2 commits from Aug 26, 2023. Now the player is beeing spawned in bed. While he is in bed (on the left side) there is a popup to press E to lay in bed. (that shouldnt be there while already beeing in bed). After waiting a bit, the player gets treated, but the animation of laying in bed is canceled and the text to get out of bed pops up. After pressing E to get out of bed, the players does the animation and gets out of bed, but getting this error https://i.imgur.com/SkrIrLt.png

these are fixed. 

These not:
EMS request text flickering.
When pressing G to request help it works even thou there's nop doctors online.
When dying of thirst of hunger or both, the laststand animation starts but no countdown text.
If I revive myself by command I get revived but the character is still playing the dead or laststand animation.

**Comment by mockdot** [comment]
The text flickering happens when this else starts:
https://github.com/Qbox-project/qbx-ambulancejob/blob/6abacd81cabfde316c4369dc90594eef2c814f2b/client/setdownedstate.lua#L57, not sure why it does the text flickering. I tried adding a Wait(0) in a couple of places in the functions or the thread, but that does not seem to be the problem.

It is true that once you are inside the time of the inlaststand where you can use [G] to call for help, if you use /revive, it will not actually revive you, you'll have to /kill and then /revive in order for the character to properly do so.

**Comment by BerkieBb** [comment]
It probably flickers because the exports yield the thread

**Comment by mockdot** [comment]
I thought of that and looked at the exports and they seem to be a return value, going to look at the threads that change that value then

**Comment by Manason** [comment]
Wonder if we should just replace this drawtext with something simpler like lib.showText

**Comment by maguhd** [comment]
Found out why ems request_help text is flickering

getDoctorCount() is not ok.
remove
 if getDoctorCount() == 0 then return end

from local function handleRequestingEms()

Untill I find another way to grab doctors on duty I just removed that function.

**Comment by mockdot** [comment]
> Wonder if we should just replace this drawtext with something simpler like lib.showText

I feel like it does bring a little of variety having this specific text shown with the 2D instead of a showText

**Comment by mockdot** [comment]
#88 fixes this.
