### ISSUE TITLE
Player's don't get revived/healed in hospital beds

### ISSUE THREAD

**Issue by ADRNALN** [Qbox-project/qb-ambulancejob#99]
### Summary

Player's don't get revived/healed in hospital beds

### Reproduction

When players check in at the front desk of the hospital with no doctors online they get sent to the beds and wait 20 seconds (time in config). Once that completes the player isn't healed or revived. I added print statements and each line prints but it seems that `TriggerEvent("hospital:client:Revive")` doesn't do anything

### Expected behavior

Healing / reviving player

### Actual behavior

Nothing happens

### Additional context

```CreateThread(function()
        Wait(5)
        print("Here")
        if isRevive then
            print("Here1")
            exports.qbx_core:Notify(Lang:t('success.being_helped'), 'success')
            print("Here2")
            Wait(Config.AIHealTimer * 1000)
            print("Here3")
            TriggerEvent("hospital:client:Revive")
            print("Here4")
        else
            CanLeaveBed = true
        end
    end)```

### Last Updated

today

### Custom Resources

no

### Resource Rename

qbx_ambulancejob

**Comment by solareon** [comment]
https://github.com/Qbox-project/qbx_ambulancejob/blob/dccb756e67782ef04ef2db1b6d9f1e635ae331bb/client/hospital.lua#L236-L262

So somewhere in here I believe needs to be a call to ```TriggerEvent('qbx_medical:client:playerRevived')``` but not sure if this the right method

**Comment by SKITTLE6969** [comment]
can confirm this, not happening and not calling the medical revive event

**Comment by mafewtm** [comment]
This was fixed in https://github.com/Qbox-project/qbx_ambulancejob/commit/7f899bb95b4a8211e5d38d72375b232f01e70cab
